### ISSUE TITLE
First compile with `compile_all.sh` fail with missing SQLITE database

### ISSUE THREAD

**Issue by josephwinston** [ryrobes/rvbbit#1]
```
...
Compiling rvbbit-backend.core
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[:creating-conn-pool "system-db"]
Syntax error macroexpanding at (sql.clj:62:1).
Execution error (SQLiteException) at org.sqlite.core.DB/newSQLException (DB.java:1179).
[SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)
```

Full report at:
/tmp/clojure-9797485789118243611.edn
Compilation failed: Subprocess failed
[clojure-9797485789118243611.txt](https://github.com/user-attachments/files/16818574/clojure-9797485789118243611.txt)

**Comment by josephwinston** [comment]
The directory ./backend/db is missing.  

A bit further:
```
Syntax error macroexpanding at (websockets.clj:6321:11).
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
data/ansi-regular.flf (No such file or directory)
```

**Comment by axelknock** [comment]
Looks like recent commits resolved issues with compiling and running, although the run-rabbit.sh script does did not target a correctly named jar, which ended up being rvbbit/backend/target/rvbbit-backend-0.1.0-alpha.1-standalone.jar
<img width="1710" alt="Screenshot 2024-08-31 at 21 21 22" src="https://github.com/user-attachments/assets/10f452b8-79bd-45df-b7d9-8efa72420dbd">
I also do not think the script should necessarily clear the the shell since a user will tend to try to run the run script immediately after building is finished, which will clear valuable debug info. I look forward to further exploration.

**Comment by ryrobes** [comment]
Revamped the whole compile-all.sh pipeline, there were lots of issues and I had lots of old dev junk artifacts everywhere. Now compile all should be the same at the binary zip release (I even create a clean dir for it  w/o src, etc).
If it still gives you problems please let me know!

**Comment by josephwinston** [comment]
Compiles and executes.  Please close.
